### ISSUE TITLE
App运行一段时间之后，曲线图绘制错误

### ISSUE THREAD

**Issue by Deerdev** [syik/BulletAnalyzer#1]
App运行一段时间之后，曲线图绘制错误

<img width="563" alt="wx20170919-183931 2x" src="https://user-images.githubusercontent.com/6970468/30588685-48c5cfb8-9d6a-11e7-8a1a-ad59aba4f6a1.png">

**Comment by heyehao2008** [comment]
用真机试试

**Comment by syik** [comment]
抱歉比较忙, 现在才看到, 你说的这种情况我也遇到过, 但是很难重现, 并且后面版本已经几乎不出现了, 若有更多信息可以提供, 谢谢关注.
