### ISSUE TITLE
厉害！比较看好这个项目！

### ISSUE THREAD

**Issue by mesoar** [syik/BulletAnalyzer#3]
很不错的想法，如果可以做一个web将数据公示出来就好了
比如 做直播行业风向标数据平台，目前小弟正在做直播系统，后续可以合作！

**Comment by syik** [comment]
呵呵, 感谢, 平时比较忙, 这个是之前做着玩的

**Comment by CoderYQ** [comment]
老哥你是把公司的项目开源出来了吗？ @syik

**Comment by syik** [comment]
怎么可能，这个项目是我在上个公司闲时写的。
